## Introduction to Python Exercises

Before you turn this problem in, make sure everything runs as expected. First, restart the kernel (in the menubar, select Kernel → Restart) and then run all cells (in the menubar, select Cell → Run All).  You can speak with others regarding the assignment but all work must be your own. 


### This is a 30 point assignment graded from answers to questions and automated tests that should be run at the bottom. Be sure to clearly label all of your answers and commit final tests at the end.  


In [3]:
NAME = "Yirong Tang"
COLLABORATORS = ["Me"]  #You can speak with others regarding the assignment, but all typed work must be your own.

In [4]:
#For some things you might need to do this in order to get tests to work. 
#%%bash 
#conda config --add channels conda-forge
#conda install --quiet ipython_unittest

### This Loads a Testing Array 
- This runs tests against your b array.  If you complete the assingment correctly, you will pass the tests. 
- **If you attempt to fake passing the tests you will receive a 0 on the assignment and it will be considered an ethical violation.**

In [5]:
%load_ext ipython_unittest
#This runs tests against your b array.  If you complete the assingment correctly, you will pass the tests. 

## Exercise-Packages

This creates an Numpy array. Numpy is a common package that we will use to work with arrays. You can read more about Numpy [here](http://www.numpy.org/). 

`a = numpy.array([2,3,4])
print(a)`

To get this to work, you will have to import the Numpy package.  

(1) Verify that Numpy is installed. How did you know?  Describe how you would you install it if it wasn't installed?

(2) Provide the code to import numpy so that the code below works.  

(3) Import numpy as np and create an array `E2` with values `5,6,7,8`.

In [6]:
#(1)
print('Question 1: we can test using the following code:')
try: 
      import numpy    
except ImportError:
      print ('numpy is not installed')

#(2)(3)

print('Question 2&3:' )

import numpy
a = numpy.array([2,3,4])
print(a)

import numpy as np
E2 = np.array([5,6,7,8])
print(E2)

Question 1: we can test using the following code:
Question 2&3:
[2 3 4]
[5 6 7 8]


## Exercise - Operations on Variables

(4) Describe what happens when you multiply an integer times a boolean? What is the resulting type? Provide examples.

(5) Describe happens when you try to multiply an integer value times a null?

(6) Take 5 to the power of 4 and assign it to a variable `E3` using an embeded function. 

In [7]:
%%unittest_main

# (4)

a1 = np.array([1,2,3],dtype=int)
b1 = np.array([0,2,3],dtype=bool)
c1 = np.multiply(a1,b1)

print('Question 4:')
print('multiply an integer with boolean',c1) 
print('c type is:',type(c1))

print('\n')


# (5)
print('Question 5:')
a2=1
print('a2 type:',type(a2))
b2=None
print('b2 type:',type(b2))
print('c2=a2*b2') 
print('When try to multiply an integer value with a null it will return an error\n') 

# (6)
print('Question 6:')
E3=5**4
print('the result of E3:',E3)
print('\n')

class TestPackages(unittest.TestCase):
    def test_packages1(self):
        self.assertTrue((a == np.array([2,3,4])).all())
    def test_packages2(self):
        self.assertTrue((E2 == np.array([5,6,7,8])).all())
    def test_variables(self):
        self.assertTrue(E3 == 625)

<IPython.core.display.Javascript object>

Question 4:
multiply an integer with boolean [0 2 3]
c type is: <class 'numpy.ndarray'>


Question 5:
a2 type: <class 'int'>
b2 type: <class 'NoneType'>
c2=a2*b2
When try to multiply an integer value with a null it will return an error

Question 6:
the result of E3: 625


...
----------------------------------------------------------------------
Ran 3 tests in 0.010s

OK


<IPython.core.display.Javascript object>

<unittest.runner.TextTestResult run=3 errors=0 failures=0>

## Exercise-Lists
Hint: [This list of functions on lists is useful.](https://docs.python.org/3/tutorial/datastructures.html)

(7) Create a list `elists1` with the following values (1,2,3,4,5).<br>

(8) Create a new list `elists2` by first creating a copy of `elist1` and then reversing the order.<br>

(9) Create a new list `elists3` by first creating a copy of `elist1` and then adding 7 8 9 to the end. *(Hint: Search for a different function if appending doesn't work.)* <br>

(10) Create a new list `elists4` by first creating a copy of `elist3` and then insert 6 between 5 and 7. 






In [8]:
%%unittest_main
#(7)
print('Question7:')
elists1=[1,2,3,4,5]
print(elists1)

#(8)
print('Question8:')
elists2=elists1.copy()
elists2.reverse()
print(elists2)

#(9)
print('Question9:')
elists3=elists1.copy()
elists3.append(7)
elists3.append(8)
elists3.append(9)
print(elists3)

#(10)
print('Question10:')
elists4=elists3.copy()
elists4.insert(5,6)
print(elists4)


class TestLists(unittest.TestCase):
    def test_list1(self):
        self.assertTrue(elists1 == [1,2,3,4,5])
    def test_list1b(self):
        self.assertTrue(type(elists1) == type([1,2,3,4,5]))
    def test_list2b(self):
        self.assertTrue(elists2 == [5,4,3,2,1])
    def test_list3(self):
        self.assertTrue(elists3 == [1,2,3,4,5,7,8,9])
    def test_list4(self):
        self.assertTrue(elists4 == [1,2,3,4,5,6,7,8,9])


<IPython.core.display.Javascript object>

Question7:
[1, 2, 3, 4, 5]
Question8:
[5, 4, 3, 2, 1]
Question9:
[1, 2, 3, 4, 5, 7, 8, 9]
Question10:
[1, 2, 3, 4, 5, 6, 7, 8, 9]
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK


<IPython.core.display.Javascript object>

<unittest.runner.TextTestResult run=5 errors=0 failures=0>

## Exercise-Sets/Dictionary
Hint: [This list of functions on lists is useful.](https://docs.python.org/3/tutorial/datastructures.html)

(11) Create a set `eset1` with the following values (1,2,3,4,5).

(12) Create a new set `eset2` the following values (1,3,6).

(13) Create a new set `eset3` that is `eset1-eset2`.

(14) Create a new set `eset4` that is the union of `eset1+eset2`.

(15) Create a new set `eset5` that includes values that are in both `eset1` and `eset2` (intersection).

(16) Create a new dict `edict1` with the following keys and associated values: st1=45; st2=32; st3=40; st4=31.

(17) Create a new variable edict2 from edict 1 where the key is st3.

In [9]:
%%unittest_main

#(11)
print('Question11:')
eset1 = set([1,2,3,4,5])
print(eset1,type(eset1))

#(12)
print('Question12:')
eset2 = set([1,3,6])
print(eset2)

#(13)
print('Question13:')
eset3 = eset1-eset2
print(eset3)

#(14)
print('Question14:')
eset4 = eset1.union(eset2)
print(eset4)

#(15)
print('Question15:')
eset5 = eset1.intersection(eset2)
print(eset5)

#(16)
print('Question16:')
edict1={'st1':45,'st2':32,'st3':40,'st4':31}
print(edict1)

#(17)
print('Question17:')
edict2 = edict1['st3']
print(edict2)

class TestSetsDicts(unittest.TestCase):
    def test_sets1(self):
        self.assertTrue(eset1 == {1,2,3,4,5})
    def test_sets1b(self):
        self.assertTrue(type(eset1) == type({1,2,3,4,5}))
    def test_sets2b(self):
         self.assertTrue(eset2 == {1,3,6})
    def test_sets3(self):
        self.assertTrue(eset3 == {2,4,5})
    def test_set4(self):
        self.assertTrue(eset4 == {1,2,3,4,5,6})
    def test_set5(self):
        self.assertTrue(eset5 == {1,3})
    def test_dict1(self):
        self.assertTrue(edict1 == {'st1' : 45, 'st2' : 32, 'st3' : 40, 'st4' : 31})
    def test_dict1b(self):
        self.assertTrue(type(edict1) == type({'st1' : 45, 'st2' : 32, 'st3' : 40, 'st4' : 31}))
    def test_dict2(self):
        self.assertTrue(edict2 == 40)



<IPython.core.display.Javascript object>

Question11:
{1, 2, 3, 4, 5} <class 'set'>
Question12:
{1, 3, 6}
Question13:
{2, 4, 5}
Question14:
{1, 2, 3, 4, 5, 6}
Question15:
{1, 3}
Question16:
{'st1': 45, 'st2': 32, 'st3': 40, 'st4': 31}
Question17:
40
.........
----------------------------------------------------------------------
Ran 9 tests in 0.017s

OK


<IPython.core.display.Javascript object>

<unittest.runner.TextTestResult run=9 errors=0 failures=0>

# Exercise-Numpy Array

(18) Create a new numpy array `nparray1` that is 3x3 and all the number 3 (should be integer type).

(19) Create a new variable `nparray1sum` that sums all of column 0.

(20) Create a new variable `nparray1mean` that takes the average of column 0. 

(21) Create a new numpy array `nparray2` that selects only column 1 of `nparray1`.

(22) Create a new numpy array `nparray3` that is equal to `nparray1` times 2 (you should not alter `nparray1`).

(23) Create a new numpy array `nparray4` that is a verticle stack of `nparray1` and `nparray3`. 

In [10]:
%%unittest_main

#(18)

print('Question18:')
nparray1 = np.full((3,3),3,dtype=int)
#nparray1=np.arange(0,9,1).reshape(3,3)

print(nparray1)

#(19)
print('Question19:')

nparray1sum = nparray1[::,0:1:].sum()
print(nparray1[::,0:1:])
print(nparray1sum)

#(20)
print('Question20:')
nparray1mean = nparray1[:,0].mean()
print(nparray1mean)

#(21)
print('Question21:')
nparray2=nparray1[::,1:2:]
print(nparray2)

#(22)
print('Question22:')
nparray3 = nparray1*2
print(nparray3)

#(23)
print('Question23:')
nparray4=np.vstack([nparray1,nparray3])
print(nparray4)

class TestNumpy(unittest.TestCase):
    def test_numpy1(self):
        self.assertTrue((nparray1 == np.full((3, 3), 3, dtype=int)).all())
    def test_numpy2(self):
         self.assertTrue(nparray1sum == 9)
    def test_numpy3(self):
        self.assertTrue(nparray1mean == 3.0)
    def test_numpy4(self):
        self.assertTrue((nparray2 == np.array([3,3,3])).all())
    def test_numpy5(self):
        self.assertTrue((nparray3 == np.full((3, 3), 6, dtype=int)).all())
    def test_numpy6(self):
        stacked=np.array([3,3,3,3,3,3,3,3,3,6,6,6,6,6,6,6,6,6]).reshape(6,3)
        self.assertTrue((nparray4 == stacked).all())


<IPython.core.display.Javascript object>

Question18:
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Question19:
[[3]
 [3]
 [3]]
9
Question20:
3.0
Question21:
[[3]
 [3]
 [3]]
Question22:
[[6 6 6]
 [6 6 6]
 [6 6 6]]
Question23:
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [6 6 6]
 [6 6 6]
 [6 6 6]]
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK


<IPython.core.display.Javascript object>

<unittest.runner.TextTestResult run=6 errors=0 failures=0>

## Exercise-Pandas
(24) Using, the Iris dataset, find the mean of the sepalLength and assign it to the `sepalLengthMean` variable using the dataframe returned from the describe command.  

(25) Create a new dataframe `iristrain` that includes the first 75 rows of the iris dataframe.

(26) Create a new dataframe `iristest` that includes the last 75 rows of the iris dataframe.

(27) Create a new series `sepalLength` from the `sepalLength` column of the iris dataframe. 



In [37]:
%%unittest_main
import pandas as pd

#(24)

import csv
csv_file_object = csv.reader(open('iris.csv', newline=''), delimiter=',')
header = next(csv_file_object)
data =[]
for row in csv_file_object:
    data.append(row)
data=np.array(data)


irisdata=data[0::,0:4].astype(np.float_)
sepalLengthMean=irisdata[::,0:1:].mean()


#(25)
f = pd.read_csv('iris.csv')
iristrain=f.iloc[0:75,:]



#(26)
f = pd.read_csv('iris.csv')
iristest = f.iloc[-75:,:]



#(27)
sepalLength = f.sepalLength


class TestPandas(unittest.TestCase):
    def test_pandas1(self):
        self.assertAlmostEqual(sepalLengthMean, 5.8433333333333337)
    def test_pandas2(self):
        self.assertTrue(iristrain.describe().sepalLength['count'] == 75.0)
    def test_pandas3(self):
        self.assertTrue(iristest.describe().sepalLength['count'] == 75.0)
    def test_pandas4(self):
        self.assertAlmostEqual(iristrain.describe().sepalLength['std'], 0.63842994352770832)
    def test_pandas5(self):
        self.assertAlmostEqual(iristest.describe().sepalLength['std'], 0.67988340282833903)
    def test_pandas6(self):
        self.assertAlmostEqual(sepalLength[134], 6.0999999999999996)



<IPython.core.display.Javascript object>

......
----------------------------------------------------------------------
Ran 6 tests in 0.063s

OK


<IPython.core.display.Javascript object>

<unittest.runner.TextTestResult run=6 errors=0 failures=0>

In [38]:
#This is a collection of all of the tests from the exercises above. 

In [40]:
%%unittest_main
class TestAll(unittest.TestCase):
    def test_packages1(self):
        self.assertTrue((a == np.array([2,3,4])).all())
    def test_packages2(self):
        self.assertTrue((E2 == np.array([5,6,7,8])).all())
    def test_variables(self):
        self.assertTrue(E3 == 625)
    def test_list1(self):
        self.assertTrue(elists1 == [1,2,3,4,5])
    def test_list1b(self):
        self.assertTrue(type(elists1) == type([1,2,3,4,5]))
    def test_list2b(self):
        self.assertTrue(elists2 == [5,4,3,2,1])
    def test_list3(self):
        self.assertTrue(elists3 == [1,2,3,4,5,7,8,9])
    def test_list4(self):
        self.assertTrue(elists4 == [1,2,3,4,5,6,7,8,9]) 
    def test_sets1(self):
        self.assertTrue(eset1 == {1,2,3,4,5})
    def test_sets1b(self):
        self.assertTrue(type(eset1) == type({1,2,3,4,5}))
    def test_sets2b(self):
         self.assertTrue(eset2 == {1,3,6})
    def test_sets3(self):
        self.assertTrue(eset3 == {2,4,5})
    def test_set4(self):
        self.assertTrue(eset4 == {1,2,3,4,5,6})
    def test_set5(self):
        self.assertTrue(eset5 == {1,3})
    def test_dict1(self):
        self.assertTrue(edict1 == {'st1' : 45, 'st2' : 32, 'st3' : 40, 'st4' : 31})
    def test_dict1b(self):
        self.assertTrue(type(edict1) == type({'st1' : 45, 'st2' : 32, 'st3' : 40, 'st4' : 31}))
    def test_dict2(self):
        self.assertTrue(edict2 == 40)
    def test_numpy1(self):
        self.assertTrue((nparray1 == np.full((3, 3), 3, dtype=int)).all())
    def test_numpy2(self):
         self.assertTrue(nparray1sum == 9)
    def test_numpy3(self):
        self.assertTrue(nparray1mean == 3.0)
    def test_numpy4(self):
        self.assertTrue((nparray2 == np.array([3,3,3])).all())
    def test_numpy5(self):
        self.assertTrue((nparray3 == np.full((3, 3), 6, dtype=int)).all())
    def test_numpy6(self):
        stacked=np.array([3,3,3,3,3,3,3,3,3,6,6,6,6,6,6,6,6,6]).reshape(6,3)
        self.assertTrue((nparray4 == stacked).all())
    def test_pandas1(self):
        self.assertAlmostEqual(sepalLengthMean, 5.8433333333333337)
    def test_pandas2(self):
        self.assertTrue(iristrain.describe().sepalLength['count'] == 75.0)
    def test_pandas3(self):
        self.assertTrue(iristest.describe().sepalLength['count'] == 75.0)
    def test_pandas4(self):
        self.assertAlmostEqual(iristrain.describe().sepalLength['std'], 0.63842994352770832)
    def test_pandas5(self):
        self.assertAlmostEqual(iristest.describe().sepalLength['std'], 0.67988340282833903)
    def test_pandas6(self):
        self.assertAlmostEqual(sepalLength[134], 6.0999999999999996)

<IPython.core.display.Javascript object>

.............................
----------------------------------------------------------------------
Ran 29 tests in 0.103s

OK


<IPython.core.display.Javascript object>

<unittest.runner.TextTestResult run=29 errors=0 failures=0>